name: ci-pr-example
run-name: ${{ github.head_ref || github.ref_name }}-ci-pr-example

on: [push]

concurrency:
  group: ci-pr-example${{ github.event.number }}
  cancel-in-progress: true


jobs:
  unit-test:
    name: "CI Unit Test"
    runs-on: 'ubuntu-22.04'
    timeout-minutes: 10 # The overall timeout
    permissions:
      actions: write
      checks: write
      contents: write
      pull-requests: write
      statuses: write

    steps:
      # checkout your repository
      - uses: actions/checkout@v4
        with:
          lfs: false
      # run tests by using the gdUnit4-action with Godot version 4.2.1 and the latest GdUnit4 release 
      - uses: MikeSchulze/gdUnit4-action@v1.0.4
        with:
          version: 'installed'
          godot-version: '4.2.1'
          paths: |
            res://test/
          timeout: 20
          report-name: test_report.xml

